# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-17 20:59
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import sisdatasources.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yearstart', models.IntegerField(choices=[(1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017)], default=2017, verbose_name='Academic Year Start')),
                ('yearend', models.IntegerField(choices=[(1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017)], default=2017, verbose_name='Academic Year End')),
                ('semester', models.CharField(choices=[('1st SEMESTER', '1st SEMESTER'), ('2nd SEMESTER', '2nd SEMESTER')], default=' ', max_length=30, verbose_name='Semester')),
                ('isactive', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default=' ', max_length=30, verbose_name='Active')),
                ('created', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Created')),
                ('modified', models.DateTimeField(auto_now_add=True, verbose_name='Date Modified')),
            ],
        ),
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yearstart', models.IntegerField(choices=[(1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017)], default=2017, verbose_name='Academic Year Start')),
                ('yearend', models.IntegerField(choices=[(1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017)], default=2017, verbose_name='Academic Year End')),
                ('grade', models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th'), ('6th', '6th'), ('7th', '7th'), ('8th', '8th'), ('9th', '9th'), ('10th', '10th'), ('11th', '11th'), ('12th', '12th')], default=' ', max_length=30, verbose_name='Class')),
                ('day', models.CharField(choices=[('MONDAY', 'MONDAY'), ('TUESDAY', 'TUESDAY'), ('WEDNESDAY', 'WEDNESDAY'), ('THURSDAY', 'THURSDAY'), ('FRIDAY', 'FRIDAY')], default=' ', max_length=30, verbose_name='Days')),
                ('classTimein', models.TimeField(blank=True, null=True, verbose_name='Time in')),
                ('classTimeout', models.TimeField(blank=True, null=True, verbose_name='Time out')),
                ('semester', models.CharField(choices=[('1st SEMESTER', '1st SEMESTER'), ('2nd SEMESTER', '2nd SEMESTER')], default=' ', max_length=30, verbose_name='Semester')),
                ('peroid', models.CharField(choices=[('1st PERIOD', '1st PERIOD'), ('2nd PERIOD', '2nd PERIOD'), ('3rd PERIOD', '3rd PERIOD'), ('1st SEMESTER EXAM', '1st SEMESTER EXAM'), ('4th PERIOD', '4th PERIOD'), ('5th PERIOD', '5th PERIOD'), ('6th PERIOD', '6th PERIOD'), ('2nd SEMESTER EXAM', '2nd SEMESTER EXAM')], default=' ', max_length=30, verbose_name='Period Test')),
                ('created', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Created')),
                ('modified', models.DateTimeField(auto_now_add=True, verbose_name='Date Modified')),
            ],
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th'), ('6th', '6th'), ('7th', '7th'), ('8th', '8th'), ('9th', '9th'), ('10th', '10th'), ('11th', '11th'), ('12th', '12th')], default=' ', max_length=30, verbose_name='Class')),
                ('totalannualfee', models.FloatField(default=0.0, verbose_name='Total Annual Fee')),
                ('created', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Created')),
                ('modified', models.DateTimeField(auto_now_add=True, verbose_name='Date Modified')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th'), ('6th', '6th'), ('7th', '7th'), ('8th', '8th'), ('9th', '9th'), ('10th', '10th'), ('11th', '11th'), ('12th', '12th')], default=' ', max_length=30, verbose_name='Class')),
                ('totalNumberOfStudents', models.IntegerField(verbose_name='Total Number of Students')),
                ('created', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Created')),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentID', models.CharField(blank=True, default='', max_length=30, verbose_name='Parent ID')),
                ('lastName', models.CharField(max_length=30, verbose_name='Last Name')),
                ('middleName', models.CharField(blank=True, max_length=30, null=True, verbose_name='Middle Name')),
                ('firstName', models.CharField(max_length=30, verbose_name='First Name')),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], default=' ', max_length=30, verbose_name='Gender')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('phone_number', models.CharField(blank=True, max_length=255, validators=[django.core.validators.RegexValidator(message="Phone number format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address')),
                ('nationality', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nationality')),
                ('occupation', models.CharField(blank=True, max_length=255, null=True, verbose_name='Occupation')),
                ('entity_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name of Entity')),
                ('entity_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Entity Address')),
                ('salary_range', models.IntegerField(blank=True, null=True, verbose_name='Salary Range')),
                ('created', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Created')),
                ('modified', models.DateTimeField(auto_now_add=True, verbose_name='Date Modified')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ReceiptNo', models.CharField(blank=True, default='', max_length=30, verbose_name='Receipt Number')),
                ('installment', models.CharField(choices=[('FIRST', 'FIRST'), ('SECOND', 'SECOND'), ('THIRD', 'THIRD'), ('FOURTH', 'FOURTH')], default=' ', max_length=30, verbose_name='Installment')),
                ('amount', models.FloatField(default=0.0, verbose_name='Amount')),
                ('digitalSignature', models.CharField(blank=True, max_length=255, null=True, verbose_name='Digital Signature')),
                ('transaction_Date', models.DateField(auto_now=True, null=True, verbose_name='Date of Transaction')),
                ('created', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Created')),
                ('modified', models.DateTimeField(auto_now_add=True, verbose_name='Date Modified')),
                ('fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sisdatasources.Fee')),
            ],
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('JANUARY', 'JANUARY'), ('FEBRUARY', 'FEBRUARY'), ('MARCH', 'MARCH'), ('APRIL', 'APRIL'), ('MAY', 'MAY'), ('JUNE', 'JUNE'), ('JULY', 'JULY'), ('AUGUST', 'AUGUST'), ('SEPTEMBER', 'SEPTEMBER'), ('OCTOBER', 'OCTOBER'), ('NOVEMBER', 'NOVEMBER'), ('DECEMBER', 'DECEMBER')], default=' ', max_length=30, verbose_name='Month Paid For')),
                ('salaryDate', models.DateField(auto_now=True, null=True, verbose_name='Paid Date')),
                ('created', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Created')),
                ('modified', models.DateTimeField(auto_now_add=True, verbose_name='Date Modified')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastName', models.CharField(max_length=30, verbose_name='Last Name')),
                ('middleName', models.CharField(blank=True, max_length=30, null=True, verbose_name='Middle Name')),
                ('firstName', models.CharField(max_length=30, verbose_name='First Name')),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], default=' ', max_length=30, verbose_name='Gender')),
                ('grade', models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th'), ('6th', '6th'), ('7th', '7th'), ('8th', '8th'), ('9th', '9th'), ('10th', '10th'), ('11th', '11th'), ('12th', '12th')], default=' ', max_length=30, verbose_name='Class')),
                ('phone_number', models.CharField(blank=True, max_length=255, validators=[django.core.validators.RegexValidator(message="Phone number format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('city', models.CharField(max_length=30, verbose_name='City')),
                ('county', models.CharField(choices=[('BOMI', 'BOMI'), ('BONG', 'BONG'), ('GBARPOLU', 'GBARPOLU'), ('GRAND BASSA', 'GRAND BASSA'), ('GRAND GEDEH', 'GRAND GEDEH'), ('GRAND KRU', 'GRAND KRU'), ('GRAND CAPE MOUNT', 'GRAND CAPE MOUNT'), ('MARGIBI', 'MARGIBI'), ('MARYLAND', 'MARYLAND'), ('MONTSERRADO', 'MONTSERRADO'), ('NIMBA', 'NIMBA'), ('LOFA', 'LOFA'), ('RIVERCESS', 'RIVERCESS'), ('RIVERGEE', 'RIVERGEE'), ('SINOE', 'SINOE')], default=None, max_length=30, verbose_name='County')),
                ('nationality', models.CharField(max_length=30, verbose_name='Nationality')),
                ('dateOfBirth', models.DateField(max_length=30, verbose_name='Date of Birth')),
                ('placeOfBirth', models.CharField(max_length=255, verbose_name='Place of Birth')),
                ('regDate', models.DateField(max_length=30, verbose_name='Registration Date')),
                ('country', models.CharField(max_length=255, verbose_name='Country')),
                ('emergency', models.CharField(blank=True, max_length=255, null=True, verbose_name='Emergency Contact')),
                ('emergency_phone', models.CharField(blank=True, max_length=255, validators=[django.core.validators.RegexValidator(message="Phone number format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone (Emergency Contact)')),
                ('transcript', models.FileField(blank=True, max_length=255, null=True, upload_to=b'', verbose_name='Transcript')),
                ('created', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Created')),
                ('modified', models.DateTimeField(auto_now_add=True, verbose_name='Date Modified')),
            ],
        ),
        migrations.CreateModel(
            name='Salarie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grossmonthlysalary', models.FloatField(default=0.0, verbose_name='Monthly Salary')),
                ('monthlyincometax', models.FloatField(verbose_name='Monthly Income Tax')),
                ('contractperiod', models.IntegerField(verbose_name='Contract Period')),
                ('accountnumber', models.CharField(max_length=255, verbose_name='Account Number')),
                ('yearstart', models.IntegerField(choices=[(1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017)], default=2017, verbose_name='Academic Year Start')),
                ('yearend', models.IntegerField(choices=[(1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017)], default=2017, verbose_name='Academic Year End')),
                ('created', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Created')),
                ('modified', models.DateTimeField(auto_now_add=True, verbose_name='Date Modified')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffID', models.CharField(blank=True, default='', max_length=30, verbose_name='Staff ID')),
                ('staff_photo', models.ImageField(max_length=255, upload_to=sisdatasources.models.upload_location, verbose_name='Teacher Picture')),
                ('lastName', models.CharField(max_length=30, verbose_name='Last Name')),
                ('middleName', models.CharField(blank=True, max_length=30, null=True, verbose_name='Middle Name')),
                ('firstName', models.CharField(max_length=30, verbose_name='First Name')),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], default=' ', max_length=30, verbose_name='Gender')),
                ('phone_number', models.CharField(blank=True, max_length=255, validators=[django.core.validators.RegexValidator(message="Phone number format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address')),
                ('dateOfBirth', models.DateField(max_length=30, verbose_name='Date of Birth')),
                ('placeOfBirth', models.CharField(max_length=255, verbose_name='Place of Birth')),
                ('nationality', models.CharField(max_length=255, verbose_name='Nationality')),
                ('numberOfSubject', models.IntegerField(verbose_name='Number of Subject Teaching')),
                ('qualification', models.CharField(max_length=255, verbose_name='Highest Qualification')),
                ('experience', models.CharField(max_length=255, verbose_name='Experience in years')),
                ('licence', models.CharField(max_length=255, verbose_name='Licence')),
                ('created', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Created')),
                ('modified', models.DateTimeField(auto_now_add=True, verbose_name='Date Modified')),
                ('users', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Staff_Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departmentName', models.CharField(choices=[('TEACHER', 'TEACHER'), ('PRINCIPAL', 'PRINCIPAL'), ('VICE PRINCIPAL', 'VICE PRINCIPAL'), ('ACCOUNTANT', 'ACCOUNTANT')], default=' ', max_length=30, verbose_name='Staff Position')),
                ('created', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Created')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sisdatasources.Staff')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentID', models.CharField(blank=True, default='', max_length=30, verbose_name='Student ID')),
                ('student_photo', models.ImageField(max_length=255, upload_to=sisdatasources.models.upload_location, verbose_name='Picture')),
                ('previous_school', models.CharField(max_length=255, verbose_name='Previous School Attended')),
                ('previous_school_address', models.CharField(max_length=255, verbose_name='Previous School Address')),
                ('last_year_attendance', models.IntegerField(choices=[(1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017)], default=2017, verbose_name='Last Year of Attendance')),
                ('level', models.CharField(choices=[('ELEMENTARY', 'ELEMENTARY'), ('JUNIOR HIGH', 'JUNIOR HIGH'), ('SENIOR HIGH', 'SENIOR HIGH')], default=None, max_length=255, verbose_name='Level')),
                ('enrollment_status', models.CharField(choices=[('ENROLLED', 'ENROLLED'), ('DID NOT ENROLL', 'DID NOT ENROLL'), ('DROPPED', 'DROPPED'), ('EXPELLED', 'EXPELLED')], default=None, max_length=255, verbose_name='Enrollment Status')),
                ('enrollment_Date', models.DateField(max_length=30, verbose_name='Enrollment Date')),
                ('created', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Created')),
                ('modified', models.DateTimeField(auto_now_add=True, verbose_name='Date Modified')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sisdatasources.Registration')),
                ('users', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('1st SEMESTER', '1st SEMESTER'), ('2nd SEMESTER', '2nd SEMESTER')], default=' ', max_length=30, verbose_name='Semester')),
                ('peroid', models.CharField(choices=[('1st PERIOD', '1st PERIOD'), ('2nd PERIOD', '2nd PERIOD'), ('3rd PERIOD', '3rd PERIOD'), ('1st SEMESTER EXAM', '1st SEMESTER EXAM'), ('4th PERIOD', '4th PERIOD'), ('5th PERIOD', '5th PERIOD'), ('6th PERIOD', '6th PERIOD'), ('2nd SEMESTER EXAM', '2nd SEMESTER EXAM')], default=' ', max_length=30, verbose_name='Period Test')),
                ('grade', models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th'), ('6th', '6th'), ('7th', '7th'), ('8th', '8th'), ('9th', '9th'), ('10th', '10th'), ('11th', '11th'), ('12th', '12th')], default=' ', max_length=30, verbose_name='Class')),
                ('day', models.CharField(choices=[('MONDAY', 'MONDAY'), ('TUESDAY', 'TUESDAY'), ('WEDNESDAY', 'WEDNESDAY'), ('THURSDAY', 'THURSDAY'), ('FRIDAY', 'FRIDAY')], default=' ', max_length=30, verbose_name='Days')),
                ('status', models.CharField(choices=[('PRESENT', 'PRESENT'), ('ABSENT', 'ABSENT')], default=' ', max_length=30, verbose_name='Status')),
                ('reasonAbsent', models.TextField(blank=True, default='', max_length=255, verbose_name='Reason Absent')),
                ('absentDate', models.DateField(auto_now=True, null=True, verbose_name='Date')),
                ('created', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Created')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sisdatasources.Student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('1st SEMESTER', '1st SEMESTER'), ('2nd SEMESTER', '2nd SEMESTER')], default=' ', max_length=30, verbose_name='Semester')),
                ('peroid', models.CharField(choices=[('1st PERIOD', '1st PERIOD'), ('2nd PERIOD', '2nd PERIOD'), ('3rd PERIOD', '3rd PERIOD'), ('1st SEMESTER EXAM', '1st SEMESTER EXAM'), ('4th PERIOD', '4th PERIOD'), ('5th PERIOD', '5th PERIOD'), ('6th PERIOD', '6th PERIOD'), ('2nd SEMESTER EXAM', '2nd SEMESTER EXAM')], default=' ', max_length=30, verbose_name='Period Test')),
                ('gradeScore', models.CharField(blank=True, default='', max_length=30, verbose_name='Grade Scored')),
                ('studenRank', models.CharField(blank=True, default='', max_length=30, verbose_name='Student Rank')),
                ('status', models.CharField(choices=[('PASSED', 'PASSED'), ('FAILED', 'FAILED')], default=' ', max_length=30, verbose_name='Status')),
                ('created', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Created')),
                ('modified', models.DateTimeField(auto_now_add=True, verbose_name='Date Modified')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sisdatasources.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('ENGLISH', 'ENGLISH'), ('MATH', 'MATH'), ('HISTORY', 'HISTORY')], default=' ', max_length=30, verbose_name='Subject')),
                ('created', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Created')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sisdatasources.Staff')),
            ],
        ),
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sisdatasources.Parent')),
                ('staff', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sisdatasources.Staff')),
                ('student', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sisdatasources.Student')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='studentmark',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sisdatasources.Subject'),
        ),
        migrations.AddField(
            model_name='salarie',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sisdatasources.Staff'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='monthly',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sisdatasources.Salarie'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sisdatasources.Staff'),
        ),
        migrations.AddField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sisdatasources.Student'),
        ),
        migrations.AddField(
            model_name='parent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sisdatasources.Student'),
        ),
        migrations.AddField(
            model_name='grade',
            name='sponsor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sisdatasources.Staff'),
        ),
        migrations.AddField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sisdatasources.Student'),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sisdatasources.Staff'),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sisdatasources.Subject'),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sisdatasources.Student'),
        ),
    ]
