# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-17 20:59
from __future__ import unicode_literals

import Absent.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sisdatasources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absentreason', models.CharField(max_length=255, verbose_name='Absent Reason')),
                ('absentfrom', models.DateField(max_length=30, verbose_name='Absent From')),
                ('absentto', models.DateField(max_length=30, verbose_name='Absent Till')),
                ('absentphoto', models.ImageField(blank=True, max_length=255, null=True, upload_to=Absent.models.upload_location, verbose_name='Absent Picture')),
                ('slug', models.SlugField(unique=True)),
                ('created', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Created')),
                ('student_id', models.ManyToManyField(related_query_name='Student', to='sisdatasources.Student')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
