# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-17 20:59
from __future__ import unicode_literals

import blog.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Blog Title')),
                ('featurephotoone', models.ImageField(max_length=255, upload_to=blog.models.upload_location, verbose_name='Feature Picture One')),
                ('featurephototwo', models.ImageField(blank=True, max_length=255, null=True, upload_to=blog.models.upload_location, verbose_name='Feature Picture Two')),
                ('featurephotothree', models.ImageField(blank=True, max_length=255, null=True, upload_to=blog.models.upload_location, verbose_name='Feature Picture Three')),
                ('content', models.CharField(blank=True, max_length=255, null=True, verbose_name='Blog Content')),
                ('emailorphone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Email or Phone')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Comment')),
                ('slug', models.SlugField(unique=True)),
                ('created', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Created')),
                ('modified', models.DateTimeField(auto_now_add=True, verbose_name='Date Modified')),
                ('users', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventtitle', models.CharField(max_length=255, verbose_name='Event Title')),
                ('eventphoto', models.ImageField(blank=True, max_length=255, null=True, upload_to=blog.models.upload_location, verbose_name='Event Photo')),
                ('eventcontent', models.CharField(max_length=255, verbose_name='Event Content')),
                ('eventdate', models.DateField(blank=True, max_length=30, null=True, verbose_name='Event Date')),
                ('slug', models.SlugField(unique=True)),
                ('created', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Created')),
                ('modified', models.DateTimeField(auto_now_add=True, verbose_name='Date Modified')),
                ('users', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
